### ISSUE TITLE
Closing unsaved buffer message (was "Keybinding for closing a tab")

### ISSUE THREAD

**Issue by captain0xff** [tombh/novim-mode#12]
Hello again. Just a request to add a keybind to close the current tab. Currently Ctrl-q closes all the tabs. But there is no way to close the current tab except going to normal mode and doing :q. Thank you. :)

**Comment by tombh** [comment]
What do you mean by a tab? I think Vim has a different concept of a tab to other editors, it seems more like what others call a layout. Are you using a plugin to manage your tabs?

This plugin already has CTRL-W to close traditionally tab-like things, though in Vim they're called buffers. CTRL-W is an important combo because it's what other editors, and more notably browsers, use for closing tabs.

**Comment by captain0xff** [comment]
@tombh sorry I am not a vim guy so didn't new. I am taking about those things that we create using the :tabnew file_name. And CTRL-W works but it closes the current tab but creates a new tab with the same name as the previous one.

**Comment by captain0xff** [comment]
![20220112_204437.jpg](https://user-images.githubusercontent.com/87000456/149168058-363e3701-b4a3-4fdf-82c9-70e82fb8ee48.jpg)

**Comment by tombh** [comment]
Hmm yeah so I think this is about the common confusion about Vim's "tabs", they're actually more like layouts. There's a good Stack Overflow answer about it here: https://stackoverflow.com/questions/26708822/why-do-vim-experts-prefer-buffers-over-tabs/26710166#26710166

So what you actually want is something like this: https://github.com/romgrk/barbar.nvim (but I think that's Neovim only, which I would recommend if you're new to Vim, it's a fork of Vim but with a much more modern approach). Otherwise you could piggyback off the tab feature in https://github.com/vim-airline/vim-airline

Either way I think this warrants me updating the README to point new Vim users in this direction.

**Comment by captain0xff** [comment]
https://github.com/romgrk/barbar.nvim works without flaw. Thanks. :]

**Comment by tombh** [comment]
great :]

**Comment by captain0xff** [comment]
Reopening the issue. Because CTRL-W works but it has some problems. If the tab(or whatever called in vims world) is opened by either C-N or :tabnew and something is written in the tab i.e the new tab has some unsaved changes the  then C-w doesn't work. It asks to use ! for force exiting.

**Comment by tombh** [comment]
![image](https://user-images.githubusercontent.com/160835/149219503-7a8bc68b-186d-418d-9e62-94d10edc441a.png)
This?

I always see this, but I've got so used to it that I never thought to change the message! Of course it's good that it doesn't delete an unsaved buffer, but 1. it should just close an empty buffer without complaining and 2. if the buffer isn't empty, but has unsaved edits, then it should give a more friendly message.

**Comment by captain0xff** [comment]
Yes the message should be more friendly like the one we see when we use CTRL-Q and have some unsaved changes.

**Comment by tombh** [comment]
I think this was fixed in #7?
