### ISSUE TITLE
error on vim startup

### ISSUE THREAD

**Issue by Natorator** [tombh/novim-mode#4]
I'm having trouble installing this plugin. 

I start with Ubuntu Xenial 16.04 LTS 
Using the packaged version 2:7.4.1689-3ubuntu1.2
I have a completely clean vi/vim config. No .vimrc , no .vim/ , nothing. 
I install https://github.com/junegunn/vim-plug according to its instructions. 
I created the .vimrc, added novim-mode ,  and ran :PlugInstall no problem. novim-mode says it was installed. Looks good so far. 

However, when I restart vim from the command line, I get this:

Error detected while processing BufEnter Auto commands for "*":
E15: Invalid expression: >execute('call s:InsertMode()')})
E116: Invalid arguments for function timer_start
Press ENTER or type command to continue

After I hit enter, I can use vim as before, but none of this plugin's features are present. 

Advice?

**Comment by tombh** [comment]
Ha, that was a silly bug of mine. Fixed and pushed.

BTW, sort of an unrelated survey question: are you particularly tied to Vim, or would you be open to using Neovim? The reason I ask is because I'm surprised by how old the default Vim is on Ubuntu 16, Vim <7.5 doesn't support `timer()` which causes a slightly annoying bug for this plugin where Insert Mode is inappropriately set for some panes, eg; NERDTree and Fugitive Blame. Latest Vim is also easy to install though, just use this PPA: `add-apt-repository ppa:laurent-boulard/vim`.

**Comment by Natorator** [comment]
Over the past 15 years, I have attempted to learn vi/vim twice. The main attraction being that it comes installed by default in Debian and Ubuntu, without even needing to so much as apt-get install it. I have never quite been able to make the switch because of the extensive differences between vim and "conventional" editors - which happens to be the precise target of your plugin here (I found it on http://hackaday.com/2017/06/21/vim-normalization/ , btw).

Given that I'd have to install a plugin manager, and then the plugin itself, that might be as much work as installing the ppa, or neovim, on a new virgin system, but then I  start asking myself how much more work that is than, say, installing git, cloning my dotfiles, and deploying my .joerc or something. 

And, of course, nano almost always comes installed by default, too. 

Thanks for the fix!

**Comment by tombh** [comment]
Yeah, I'm similar to you, in that I've given Vim a serious go more than once, but never became fluent enough to fully make the transition. Thanks for that link BTW, I had seen it already because Github helpfully keeps a log of referrers.

It has crossed my mind that a little `curl novim.sh | sh` might be appropriate here, it would be trivial for sure, but it's only applicable to people that don't already have a `.vimrc` setup. I'll if there's any more demand.
